name: scanly
description: "Ứng dụng scan tài liệu cá nhân và bộ công cụ PDF."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.13.0
  firebase_auth: ^6.5.7
  flutter_bloc: ^9.1.1
  equatable: ^2.1.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
   - images/